#!/usr/bin/env bun
/**
 * Merge-strategy guard for the id-keyed JSONL state files (warren-9c90).
 *
 * The seeds and mulch state files are JSONL whose writers REWRITE rows in
 * place. `merge=union` keeps BOTH sides' lines for a conflicting hunk with
 * no markers, so a concurrent rewrite of one row silently produced two
 * contradictory copies of it and git reported a clean merge. Those files
 * now resolve to `merge=seeds-jsonl`, the real 3-way driver in
 * `scripts/merge-seeds-jsonl.ts`.
 *
 * WHY THIS GUARD EXISTS, and why it is not paranoia: the `merge=union`
 * lines are not hand-written config. They are GENERATED by the tools and
 * one of them ENFORCES its own line:
 *
 *   - `sd init` writes them from `MERGE_UNION_LINES` (seeds
 *     src/commands/init.ts) and re-runs BACKFILL any that are missing.
 *   - `sd doctor` reports a missing line as `Missing merge=union
 *     gitattributes entries` with `fixable: true`, and `sd doctor --fix`
 *     APPENDS it back (seeds src/commands/doctor.ts).
 *   - mulch writes its own line from `GITATTRIBUTES_LINE`
 *     (mulch src/utils/config.ts).
 *
 * All of them test with a literal substring match on the union line, so
 * they cannot see that a correct driver already covers the path. Git
 * resolves `.gitattributes` LAST MATCH WINS, so an appended union line
 * OVERRIDES the driver above it and silently restores the original bug —
 * while `sd doctor` reports the repo as healthy. That is a regression no
 * diff review reliably catches, because the appended line looks like the
 * tool tidying up after itself.
 *
 * The guard therefore asks GIT what it actually resolves, via
 * `git check-attr`, rather than parsing `.gitattributes` and re-deriving
 * precedence. Whatever git says is the truth that matters at merge time.
 *
 * Upstream fix: seeds-6e2d (stop emitting union for rewritten files, ship
 * the driver from `sd init`, and make `doctor` validate the resolved
 * strategy instead of substring-matching). Until that lands, a
 * `sd doctor` warning about a "missing" merge=union entry on these paths
 * is EXPECTED and must NOT be "fixed".
 *
 * Chained into `bun run lint` rather than registered as its own gate:
 * `scripts/check-all.ts` is byte-identical to the l5-toolkit template and
 * its gate vocabulary is frozen, so a repo-specific assertion folds into
 * an existing gate. Also runnable directly:
 * `bun run check:merge-strategy`.
 */

import { spawnSync } from "node:child_process";

/** Paths whose rows are rewritten in place, so union merge is unsafe. */
export const GUARDED_PATHS = [
	".seeds/issues.jsonl",
	".seeds/templates.jsonl",
	".seeds/plans.jsonl",
	".mulch/expertise/forge.jsonl",
] as const;

export const REQUIRED_DRIVER = "seeds-jsonl";

/** Resolves the merge attribute git reports for a path. Injected so the
 * evaluation is testable without a git fixture. */
export type MergeAttrResolver = (path: string) => string;

/** Ask git which merge attribute it actually resolves for a path. */
function resolvedMergeAttr(path: string): string {
	const res = spawnSync("git", ["check-attr", "merge", "--", path], { encoding: "utf8" });
	if (res.status !== 0) {
		throw new Error(`git check-attr failed for ${path}: ${res.stderr.trim()}`);
	}
	// Output shape: "<path>: merge: <value>"
	const out = res.stdout.trim();
	const value = out.slice(out.lastIndexOf(":") + 1).trim();
	if (value === "") throw new Error(`could not parse check-attr output: ${out}`);
	return value;
}

/**
 * Evaluate the resolved merge attribute for each guarded path.
 * Returns one message per violation; an empty array means the tree is safe.
 */
export function evaluate(
	paths: readonly string[],
	resolve: MergeAttrResolver = resolvedMergeAttr,
): string[] {
	const failures: string[] = [];

	for (const path of paths) {
		let attr: string;
		try {
			attr = resolve(path);
		} catch (err) {
			failures.push(`${path} — ${(err as Error).message}`);
			continue;
		}

		if (attr === REQUIRED_DRIVER) continue;

		if (attr === "union") {
			failures.push(
				`${path} — resolves to merge=union, which silently keeps both copies of a ` +
					`rewritten row. A later .gitattributes line has overridden ` +
					`merge=${REQUIRED_DRIVER}. This is what \`sd doctor --fix\` and \`sd init\` ` +
					`do when they "restore" the generated union line — remove the appended ` +
					`line, do not re-add it (see seeds-6e2d).`,
			);
		} else {
			failures.push(`${path} — resolves to merge=${attr}, expected merge=${REQUIRED_DRIVER}.`);
		}
	}

	return failures;
}

function main(): void {
	const failures = evaluate(GUARDED_PATHS);

	if (failures.length > 0) {
		console.error("check:merge-strategy — FAILED");
		for (const f of failures) console.error(`  ${f}`);
		process.exit(1);
	}

	console.log(
		`check:merge-strategy — ok (${GUARDED_PATHS.length} paths resolve to merge=${REQUIRED_DRIVER})`,
	);
}

if (import.meta.main) main();
