/**
 * `warren config migrate` — convert a project's legacy `.warren/defaults.json`
 * into the warren-5840 YAML layout in place.
 *
 * Mechanics:
 *   1. Read and schema-validate the legacy `defaults.json`.
 *   2. Pull any `preview` block out into a top-level `.warren/preview.yaml`.
 *   3. Write the remaining fields to `.warren/config.yaml`.
 *   4. Delete `.warren/defaults.json` (the deprecation source) so doctor /
 *      readyz / load no longer emit the deprecation warning on the next
 *      refresh.
 *
 * Refuses to clobber an existing `config.yaml` or `preview.yaml` — the
 * operator either already migrated (in which case `defaults.json` is stale
 * and should be deleted by hand) or has uncommitted edits we'd silently
 * lose. Schema failures in the source file abort the migrate with the
 * underlying error: a malformed `defaults.json` is fixed by editing, not
 * by converting.
 *
 * Targets the same `--cwd` / `--project <id>` pair that `warren init`
 * uses — operators own the commit + push themselves; the command is a
 * pure local file edit.
 */

import { existsSync } from "node:fs";
import { readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { dump } from "js-yaml";
import type { WarrenClient } from "../../client/index.ts";
import { ValidationError } from "../../core/errors.ts";
import {
	WARREN_CONFIG_DIR,
	WARREN_CONFIG_FILES,
	warrenConfigRelativePath,
} from "../../warren-config/config.ts";
import {
	type DefaultsConfig,
	type PreviewConfig,
	parseDefaultsConfig,
} from "../../warren-config/schema.ts";
import type { CliContext } from "../output.ts";
import { commandFailure, formatError, writeResult } from "../output.ts";
import { resolveTargetDir } from "./target-dir.ts";

export type ConfigMigrateArgs =
	| { readonly mode: "cwd"; readonly cwd: string }
	| { readonly mode: "project"; readonly projectId: string };

export interface ConfigMigrateDeps {
	/**
	 * Remote warren client (warren-97a2). `--project` resolves the clone
	 * path via `GET /projects/:id`; the CLI no longer opens the server's DB.
	 */
	readonly client: WarrenClient;
}

export interface ConfigMigrateResult {
	readonly exitCode: number;
}

const CONFIG_HEADER = `# .warren/config.yaml — per-project warren defaults (warren-5840 layout).
#
# Generated by 'warren config migrate' from .warren/defaults.json.
# See docs/design/warren-config.md for the schema.
`;

const PREVIEW_HEADER = `# .warren/preview.yaml — per-run preview environment (warren-5840, docs/design/preview-environments.md).
#
# Hoisted out of .warren/defaults.json by 'warren config migrate'. The
# top-level document is the preview block itself, not nested under a
# 'preview:' key.
`;

export async function runConfigMigrate(
	context: CliContext,
	deps: ConfigMigrateDeps,
	args: ConfigMigrateArgs,
): Promise<ConfigMigrateResult> {
	try {
		const targetDir = await resolveTargetDir(deps.client, args);
		const warrenDir = join(targetDir, WARREN_CONFIG_DIR);
		const legacyAbs = join(warrenDir, WARREN_CONFIG_FILES.defaults);
		const configAbs = join(warrenDir, WARREN_CONFIG_FILES.config);
		const previewAbs = join(warrenDir, WARREN_CONFIG_FILES.preview);

		if (!existsSync(legacyAbs)) {
			throw new ValidationError(
				`nothing to migrate: ${warrenConfigRelativePath("defaults")} does not exist in ${warrenDir}`,
				{
					recoveryHint: "if you already migrated by hand, this is a no-op and you can ignore it",
				},
			);
		}
		if (existsSync(configAbs)) {
			throw new ValidationError(
				`refusing to overwrite existing ${warrenConfigRelativePath("config")} at ${configAbs}`,
				{
					recoveryHint:
						"resolve the existing config.yaml first (e.g. delete it after merging by hand), then re-run",
				},
			);
		}
		if (existsSync(previewAbs)) {
			throw new ValidationError(
				`refusing to overwrite existing ${warrenConfigRelativePath("preview")} at ${previewAbs}`,
				{
					recoveryHint:
						"resolve the existing preview.yaml first (e.g. delete it after merging by hand), then re-run",
				},
			);
		}

		const raw = await readFile(legacyAbs, "utf8");
		const trimmed = raw.trim();
		let document: unknown;
		if (trimmed === "") {
			document = undefined;
		} else {
			try {
				document = JSON.parse(raw);
			} catch (err) {
				throw new ValidationError(
					`failed to parse ${warrenConfigRelativePath("defaults")}: ${formatError(err)}`,
					{
						recoveryHint:
							"fix the JSON syntax in defaults.json by hand, then re-run `warren config migrate`",
					},
				);
			}
		}

		const parsed = parseDefaultsConfig(document);
		if (!parsed.ok) {
			throw new ValidationError(
				`schema validation failed for ${warrenConfigRelativePath("defaults")}: ${parsed.message}`,
				{
					recoveryHint:
						"fix the schema violation in defaults.json by hand, then re-run `warren config migrate`",
				},
			);
		}

		const { configBlock, previewBlock } = splitPreview(parsed.value);

		const writtenFiles: string[] = [];
		const configBody = renderConfig(configBlock);
		await writeFile(configAbs, configBody, "utf8");
		writtenFiles.push(warrenConfigRelativePath("config"));

		if (previewBlock !== null) {
			const previewBody = renderPreview(previewBlock);
			await writeFile(previewAbs, previewBody, "utf8");
			writtenFiles.push(warrenConfigRelativePath("preview"));
		}

		await rm(legacyAbs, { force: true });

		writeResult(
			context,
			{
				ok: true,
				migrated: {
					root: targetDir,
					removed: warrenConfigRelativePath("defaults"),
					written: writtenFiles,
					previewHoisted: previewBlock !== null,
				},
			},
			`✔ migrated .warren/defaults.json in ${targetDir} — wrote ${writtenFiles.join(", ")}`,
		);
		return { exitCode: 0 };
	} catch (err) {
		return commandFailure(context, err);
	}
}

function splitPreview(defaults: DefaultsConfig): {
	configBlock: DefaultsConfig;
	previewBlock: PreviewConfig | null;
} {
	const { preview, ...rest } = defaults;
	return {
		configBlock: rest,
		previewBlock: preview ?? null,
	};
}

function renderConfig(config: DefaultsConfig): string {
	if (Object.keys(config).length === 0) {
		return `${CONFIG_HEADER}{}\n`;
	}
	return `${CONFIG_HEADER}${dump(config, { lineWidth: 100, noRefs: true })}`;
}

function renderPreview(preview: PreviewConfig): string {
	return `${PREVIEW_HEADER}${dump(preview, { lineWidth: 100, noRefs: true })}`;
}
